LICENSE, templates/openapi-legacy.yaml, templates/openapi.yaml
=> Specify IETF Trust licence

xml2rfc_compat/static/schemas/SVG-1.2-RFC.xsd, xml2rfc_compat/static/schemas/ns1.xsd, xml2rfc_compat/static/schemas/v3.xsd, xml2rfc_compat/static/schemas/xlink.xsd, xml2rfc_compat/static/schemas/xml.xsd, xml2rfc_compat/tests.py
=> Validate XML output against XSD schema

docs/topics/production-setup.rst, requirements.txt, xml2rfc_compat/adapters.py
This should address https://github.com/ietf-tools/bibxml-service/issues/256, https://github.com/ietf-tools/bibxml-service/issues/252, https://github.com/ietf-tools/bibxml-service/issues/225#issuecomment-1204650602.
=> Updates from Ribose’s fork

main/templates/browse/search_forms.html
=> fix: change <input> with <button> for hovering cursor style

docs/topics/architecture.rst
=> fix: update docs on architecture and link to wiki, fixes #273

bib_models/util.py, requirements.txt
Should address #277, #281, #276
=> Normalize some source data variations

bibxml/xml2rfc_adapters.py, templates/openapi-legacy.yaml, xml2rfc_compat/views.py
=> Anchor-related tweaks

requirements.txt
Fix for https://github.com/ietf-tools/bibxml-service/issues/312
=> bump relaton version

xml2rfc_compat/serializers/__init__.py, xml2rfc_compat/serializers/reference.py, xml2rfc_compat/tests/test_serializers.py
=> Remove `<format>` tag (deprecated in v3 (7991))

xml2rfc_compat/serializers/reference.py, xml2rfc_compat/tests/test_serializers.py
Fix for https://github.com/ietf-tools/bibxml-service/issues/261
=> Ignore docid whose scope == "trademark"

xml2rfc_compat/serializers/reference.py
=> chore: replace reference target URL for DOI items

bibxml/xml2rfc_adapters.py
=> fix: Serve RFC URLs without leading 0s + enable serving RFC > 9999

doi/crossref.py
=> chore: cache Crossref requests + improve error message

sources/app.py, sources/signals.py
=> chore: delete SourceIndexationOutcome entries older than 9 days

common/git.py, main/tests/test_apis.py
=> fix: mypy errors

main/query.py, main/templates/relaton/contributor.html, main/templates/relaton/person_name.html
=> fix: given name in citation details page + search filtering URL

main/query.py, xml2rfc_compat/serializers/__init__.py, xml2rfc_compat/tests/test_serializers.py
=> chore: set target for referencegroup

xml2rfc_compat/serializers/authors.py
=> fix: add condition to assert content is not None

.github/workflows/helm-checks.yml, .github/workflows/publish.yml, .gitignore, helm/.helmignore, helm/Chart.yaml, helm/templates/NOTES.txt, helm/templates/_helpers.tpl, helm/templates/deployment.yaml, helm/templates/hpa.yaml, helm/templates/ingress.yaml, helm/templates/service.yaml, helm/templates/serviceaccount.yaml, helm/templates/tests/test-connection.yaml, helm/values.yaml
=> feat: Helm chart for bibxml-service

helm/templates/deployment.yaml, helm/templates/service.yaml, helm/values.yaml
- selector labels fixed to expose service in k8s
- updated environment template for SNAPSHOT env var to allow searching to work
=> fix: selectorLabels updates to expose service on pod

docs/index.rst
=> docs: Fix RFP link

bibxml/xml2rfc_adapters.py, xml2rfc_compat/tests/test_adapters.py
=> feat: Use https scheme for IANA target URLs

bibxml/xml2rfc_adapters.py, xml2rfc_compat/tests/test_adapters.py
=> fix: Remove date from IANA BibXML reference

main/templates/citation/export.html
=> feat: Provide xml2rfc compatible BibXML for BibXML download button

.github/workflows/kustomize-checks.yml
This will fail until #449 is merged.
=> ci: Add kustomize configuration check

k8s/bib.yaml
This is to force new pod creation on every deploy.
=> chore: Provide DEPLOY_UID to force pod creation on every deploy

k8s/bib.yaml, k8s/kustomization.yaml, k8s/settings.py
This PR is for staging testing.
This updates bibxml-service to look at `rc` branch instead of `main` branch.
=> build(temp): Use custom branch for relaton data

datatracker/internet_drafts.py
=> fix(I-D): Construct the correct target for updated I-Ds

bibxml/settings.py, bibxml/urls.py, requirements.txt
=> feat: Add health check
